services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    build: .
    depends_on:
      - redis
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    env_file:
    - .env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
    - .env
volumes:
  postgres: